// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenNotepad(arg1) {
  return window['go']['main']['App']['OpenNotepad'](arg1);
}

export function RunExecutable(arg1) {
  return window['go']['main']['App']['RunExecutable'](arg1);
}
