// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenNotepad(arg1:string):Promise<void>;

export function RunExecutable(arg1:string):Promise<void>;
